/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.test;

/**
 *
 * @author Kenneth
 */
public class GuiAgregar extends javax.swing.JPanel {

    GUI frame;
    /**
     * Creates new form GuiAgregar
     * @param mainFrame
     */
    public GuiAgregar(GUI mainFrame) {
        this.frame = mainFrame;
        initComponents();
        
        this.layerAddGame.setVisible(false);
        this.layerAddConsole.setVisible(true);
    }

    
    public void mostrar(int e){
        if(e == 0){
            this.layerAddGame.setVisible(true);
            this.layerAddGame.setLocation(5, 10);
            this.layerAddConsole.setVisible(false);
        }else{
            this.layerAddConsole.setVisible(true);
            this.layerAddConsole.setLocation(5, 10);
            this.layerAddGame.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layerAddGame = new javax.swing.JLayeredPane();
        lblEmpresa = new javax.swing.JLabel();
        lblRate = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtNombre1 = new javax.swing.JTextField();
        btnAddGame = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        lblDescrip = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescrip = new javax.swing.JTextArea();
        txtEmp = new javax.swing.JTextField();
        layerAddConsole = new javax.swing.JLayeredPane();
        txtAnioConsole = new javax.swing.JTextField();
        lblDescripConsole = new javax.swing.JLabel();
        txtNombreConsole1 = new javax.swing.JTextField();
        lblEmpresaConsole = new javax.swing.JLabel();
        btnInicioConsole = new javax.swing.JButton();
        btnAddConsole1 = new javax.swing.JButton();
        lblNombreConsole1 = new javax.swing.JLabel();
        txtEmpConsole1 = new javax.swing.JTextField();

        layerAddGame.setBackground(new java.awt.Color(51, 51, 51));
        layerAddGame.setOpaque(true);
        layerAddGame.setPreferredSize(new java.awt.Dimension(370, 398));

        lblEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpresa.setText("Empresa:");

        lblRate.setBackground(new java.awt.Color(255, 255, 255));
        lblRate.setForeground(new java.awt.Color(255, 255, 255));
        lblRate.setText("Rate");

        txtRate.setText("Rate");

        txtAnio.setText("Año");
        txtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioActionPerformed(evt);
            }
        });

        txtNombre1.setText("Nombre");

        btnAddGame.setBackground(new java.awt.Color(0, 102, 102));
        btnAddGame.setText("Agregar");
        btnAddGame.setBorderPainted(false);
        btnAddGame.setFocusable(false);
        btnAddGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGameActionPerformed(evt);
            }
        });

        btnInicio.setBackground(new java.awt.Color(0, 102, 102));
        btnInicio.setText("Inicio");
        btnInicio.setBorderPainted(false);
        btnInicio.setFocusable(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        lblDescrip.setForeground(new java.awt.Color(255, 255, 255));
        lblDescrip.setText("Descripción");

        lblAnio.setBackground(new java.awt.Color(255, 255, 255));
        lblAnio.setForeground(new java.awt.Color(255, 255, 255));
        lblAnio.setText("Año:");

        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");

        txtDescrip.setColumns(20);
        txtDescrip.setRows(5);
        jScrollPane1.setViewportView(txtDescrip);

        txtEmp.setText("Empresa");
        txtEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layerAddGameLayout = new javax.swing.GroupLayout(layerAddGame);
        layerAddGame.setLayout(layerAddGameLayout);
        layerAddGameLayout.setHorizontalGroup(
            layerAddGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layerAddGameLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layerAddGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layerAddGameLayout.createSequentialGroup()
                        .addGroup(layerAddGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layerAddGameLayout.createSequentialGroup()
                                .addComponent(lblAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(lblRate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layerAddGameLayout.createSequentialGroup()
                                .addComponent(lblEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layerAddGameLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layerAddGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layerAddGameLayout.createSequentialGroup()
                                .addGroup(layerAddGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layerAddGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layerAddGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layerAddGameLayout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(btnAddGame, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 24, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layerAddGameLayout.setVerticalGroup(
            layerAddGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layerAddGameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layerAddGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layerAddGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layerAddGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddGame, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        layerAddGame.setLayer(lblEmpresa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerAddGame.setLayer(lblRate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerAddGame.setLayer(txtRate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerAddGame.setLayer(txtAnio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerAddGame.setLayer(txtNombre1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerAddGame.setLayer(btnAddGame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerAddGame.setLayer(btnInicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerAddGame.setLayer(lblDescrip, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerAddGame.setLayer(lblAnio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerAddGame.setLayer(lblNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerAddGame.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerAddGame.setLayer(txtEmp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        layerAddConsole.setBackground(new java.awt.Color(51, 51, 51));
        layerAddConsole.setOpaque(true);
        layerAddConsole.setPreferredSize(new java.awt.Dimension(370, 398));

        txtAnioConsole.setText("Año");
        txtAnioConsole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioConsoleActionPerformed(evt);
            }
        });

        lblDescripConsole.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripConsole.setText("Año:");

        txtNombreConsole1.setText("Nombre");
        txtNombreConsole1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreConsole1ActionPerformed(evt);
            }
        });

        lblEmpresaConsole.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpresaConsole.setText("Empresa:");

        btnInicioConsole.setBackground(new java.awt.Color(0, 102, 102));
        btnInicioConsole.setText("Inicio");
        btnInicioConsole.setBorderPainted(false);
        btnInicioConsole.setFocusable(false);
        btnInicioConsole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioConsoleActionPerformed(evt);
            }
        });

        btnAddConsole1.setBackground(new java.awt.Color(0, 102, 102));
        btnAddConsole1.setText("Agregar");
        btnAddConsole1.setBorderPainted(false);
        btnAddConsole1.setFocusable(false);

        lblNombreConsole1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreConsole1.setText("Nombre:");

        txtEmpConsole1.setText("Empresa");
        txtEmpConsole1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpConsole1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layerAddConsoleLayout = new javax.swing.GroupLayout(layerAddConsole);
        layerAddConsole.setLayout(layerAddConsoleLayout);
        layerAddConsoleLayout.setHorizontalGroup(
            layerAddConsoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layerAddConsoleLayout.createSequentialGroup()
                .addGroup(layerAddConsoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layerAddConsoleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layerAddConsoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAnioConsole, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombreConsole1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layerAddConsoleLayout.createSequentialGroup()
                                .addComponent(lblDescripConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 156, Short.MAX_VALUE))
                            .addComponent(txtEmpConsole1)))
                    .addGroup(layerAddConsoleLayout.createSequentialGroup()
                        .addGroup(layerAddConsoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layerAddConsoleLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnAddConsole1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layerAddConsoleLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblEmpresaConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layerAddConsoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layerAddConsoleLayout.createSequentialGroup()
                    .addContainerGap(219, Short.MAX_VALUE)
                    .addComponent(btnInicioConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layerAddConsoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layerAddConsoleLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblNombreConsole1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layerAddConsoleLayout.setVerticalGroup(
            layerAddConsoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layerAddConsoleLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(txtNombreConsole1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblDescripConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAnioConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblEmpresaConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmpConsole1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddConsole1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layerAddConsoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layerAddConsoleLayout.createSequentialGroup()
                    .addContainerGap(336, Short.MAX_VALUE)
                    .addComponent(btnInicioConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)))
            .addGroup(layerAddConsoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layerAddConsoleLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(lblNombreConsole1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(347, Short.MAX_VALUE)))
        );
        layerAddConsole.setLayer(txtAnioConsole, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerAddConsole.setLayer(lblDescripConsole, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerAddConsole.setLayer(txtNombreConsole1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerAddConsole.setLayer(lblEmpresaConsole, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerAddConsole.setLayer(btnInicioConsole, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerAddConsole.setLayer(btnAddConsole1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerAddConsole.setLayer(lblNombreConsole1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layerAddConsole.setLayer(txtEmpConsole1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(layerAddGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(layerAddConsole, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(layerAddGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(layerAddConsole, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnioConsoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioConsoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioConsoleActionPerformed

    private void txtEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpActionPerformed

    private void txtNombreConsole1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreConsole1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreConsole1ActionPerformed

    private void txtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        frame.Inicio();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnAddGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddGameActionPerformed

    private void txtEmpConsole1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpConsole1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpConsole1ActionPerformed

    private void btnInicioConsoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioConsoleActionPerformed
        // TODO add your handling code here:
        frame.Inicio();
    }//GEN-LAST:event_btnInicioConsoleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddConsole1;
    private javax.swing.JButton btnAddGame;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnInicioConsole;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLayeredPane layerAddConsole;
    private javax.swing.JLayeredPane layerAddGame;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblDescrip;
    private javax.swing.JLabel lblDescripConsole;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblEmpresaConsole;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreConsole1;
    private javax.swing.JLabel lblRate;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtAnioConsole;
    private javax.swing.JTextArea txtDescrip;
    private javax.swing.JTextField txtEmp;
    private javax.swing.JTextField txtEmpConsole1;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombreConsole1;
    private javax.swing.JTextField txtRate;
    // End of variables declaration//GEN-END:variables
}
