/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.test;

/**
 *
 * @author Kenneth
 */
public class Test extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLeft1 = new javax.swing.JButton();
        btnRight1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnLeft2 = new javax.swing.JButton();
        btnRight2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnLeft3 = new javax.swing.JButton();
        btnRight3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnLeft4 = new javax.swing.JButton();
        btnRight4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lbltext = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        btnLeft1.setBorderPainted(false);
        btnLeft1.setContentAreaFilled(false);
        btnLeft1.setFocusable(false);
        btnLeft1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeft1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLeft1);
        btnLeft1.setBounds(10, 100, 61, 75);

        btnRight1.setBorderPainted(false);
        btnRight1.setContentAreaFilled(false);
        btnRight1.setFocusable(false);
        btnRight1.setHideActionText(true);
        btnRight1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRight1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRight1);
        btnRight1.setBounds(650, 110, 61, 75);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        btnLeft2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/test/l2.png"))); // NOI18N
        btnLeft2.setBorderPainted(false);
        btnLeft2.setContentAreaFilled(false);
        btnLeft2.setFocusable(false);
        btnLeft2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/test/l.png"))); // NOI18N
        btnLeft2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeft2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnLeft2);
        btnLeft2.setBounds(10, 54, 61, 75);

        btnRight2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/test/r2.png"))); // NOI18N
        btnRight2.setBorderPainted(false);
        btnRight2.setContentAreaFilled(false);
        btnRight2.setFocusable(false);
        btnRight2.setHideActionText(true);
        btnRight2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/test/2805.png"))); // NOI18N
        jPanel2.add(btnRight2);
        btnRight2.setBounds(582, 54, 61, 75);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(33, 41, 0, 0);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(null);

        btnLeft3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/test/l2.png"))); // NOI18N
        btnLeft3.setBorderPainted(false);
        btnLeft3.setContentAreaFilled(false);
        btnLeft3.setFocusable(false);
        btnLeft3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/test/l.png"))); // NOI18N
        btnLeft3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeft3ActionPerformed(evt);
            }
        });
        jPanel3.add(btnLeft3);
        btnLeft3.setBounds(10, 54, 61, 75);

        btnRight3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/test/r2.png"))); // NOI18N
        btnRight3.setBorderPainted(false);
        btnRight3.setContentAreaFilled(false);
        btnRight3.setFocusable(false);
        btnRight3.setHideActionText(true);
        btnRight3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/test/2805.png"))); // NOI18N
        jPanel3.add(btnRight3);
        btnRight3.setBounds(582, 54, 61, 75);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(null);

        btnLeft4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/test/l2.png"))); // NOI18N
        btnLeft4.setBorderPainted(false);
        btnLeft4.setContentAreaFilled(false);
        btnLeft4.setFocusable(false);
        btnLeft4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/test/l.png"))); // NOI18N
        btnLeft4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeft4ActionPerformed(evt);
            }
        });
        jPanel4.add(btnLeft4);
        btnLeft4.setBounds(10, 54, 61, 75);

        btnRight4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/test/r2.png"))); // NOI18N
        btnRight4.setBorderPainted(false);
        btnRight4.setContentAreaFilled(false);
        btnRight4.setFocusable(false);
        btnRight4.setHideActionText(true);
        btnRight4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/test/2805.png"))); // NOI18N
        jPanel4.add(btnRight4);
        btnRight4.setBounds(582, 54, 61, 75);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(33, 41, 0, 0);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(33, 41, 0, 0);

        jLabel1.setText("Imagen");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 70, 200, 200);

        lblCategoria.setBackground(new java.awt.Color(102, 102, 102));
        lblCategoria.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria.setText(" Juegos");
        lblCategoria.setOpaque(true);
        jPanel1.add(lblCategoria);
        lblCategoria.setBounds(0, 0, 740, 40);

        lbltext.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lbltext.setForeground(new java.awt.Color(255, 255, 255));
        lbltext.setText("Nombre:");
        jPanel1.add(lbltext);
        lbltext.setBounds(290, 50, 360, 40);

        jTextField1.setText("Descripción");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(290, 100, 350, 170);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addGap(131, 131, 131))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeft1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeft1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLeft1ActionPerformed

    private void btnRight1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRight1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRight1ActionPerformed

    private void btnLeft2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeft2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLeft2ActionPerformed

    private void btnLeft3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeft3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLeft3ActionPerformed

    private void btnLeft4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeft4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLeft4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeft1;
    private javax.swing.JButton btnLeft2;
    private javax.swing.JButton btnLeft3;
    private javax.swing.JButton btnLeft4;
    private javax.swing.JButton btnRight1;
    private javax.swing.JButton btnRight2;
    private javax.swing.JButton btnRight3;
    private javax.swing.JButton btnRight4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lbltext;
    // End of variables declaration//GEN-END:variables
}
